// <auto-generated />
using CEPCounsult.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CEPCounsult.Migrations
{
    [DbContext(typeof(CEPContext))]
    [Migration("20210723184707_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CEPCounsult.Models.CEP", b =>
                {
                    b.Property<int>("CepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Cep")
                        .HasColumnType("char(9)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GIA")
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IBGE")
                        .HasColumnType("int");

                    b.Property<string>("Localidade")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UF")
                        .HasColumnType("char(2)");

                    b.Property<long>("Unidade")
                        .HasColumnType("bigint");

                    b.HasKey("CepID");

                    b.ToTable("CEP");
                });
#pragma warning restore 612, 618
        }
    }
}
